### PR TITLE
Pull request - add 4 new coins

### PR DESCRIPTION
**Pull request by ghost**
Aquariuscoin
Lanacoin
Tajcoin
Nevacoin

All established good standing coins.

### CODE REVIEW

**Comment by MichaelMure** [comment]
Hi !

Thanks for all of this. I should really find some brain time to do a release.

The coin addition seems fine. However, you touched the `index.html` file by removing the trailing whitespace. This could be a good change but in this case you should do it on the source files (/src/*) as well. Otherwise, the next time someone use grunt to build `index.html` it will be overwritten.

**Comment by ghost** [comment]
@MichaelMure I didnt even realize I did that, my editor decided to do it for me when I saved.

Anyway, I did the same in src/*

Hope its ok now

**Comment by MichaelMure** [comment]
Manually merged.

I changed my mind and removed your changes in the crypto code. It's better to leave it untouched and identical to bitaddress.org, unless it's for a good reason.

**Comment by MichaelMure** [comment]
Hey, it's now merged and live on https://walletgenerator.net/ !

Sorry for the very long delay.

**Pull request closed without merging**
