### PR TITLE
add lomocoin support

### PR DESCRIPTION
**Pull request by liujiopen**

### CODE REVIEW

**Comment by MichaelMure** [comment]
Thanks, it looks good. It will be in the next release.

However you should have the same change in `index.html` as in `janin.currency.js`. You can use `grunt` to do that or do it manually.

Out of curiosity, is there a reason why you made this pull-request juste a few jours after the last release ? You are not the first to do that so I'm wondering.

**Comment by liujiopen** [comment]
Well, I sent you a email with the attachment file about the support for Lomocoin , but no response.

I just guess maybe you missed the email and a pr may accelerate the process.

And I didn't noticed the site's last release any more, it must be a coincidence.

Sorry for your additional work.

**Comment by MichaelMure** [comment]
No problem.

I did receive the email but I'm currently traveling so I can't be that much active. I received your email a mere 7 hours after the last release, I was just wondering if it was related.

**Comment by liujiopen** [comment]
Thank you. 

I see. 

Hope you will add that update in the live website  in the near future.  ; )

**Comment by MichaelMure** [comment]
It's online, sorry for the delay ! :-)

**Comment by liujiopen** [comment]
thanks for your work.

2017-09-02 18:10 GMT+08:00 Michael Muré <notifications@github.com>:

**Pull request merged**
