### PR TITLE
Add support for Animecoin

### PR DESCRIPTION
**Pull request by testzcrypto**

### CODE REVIEW

**Comment by MichaelMure** [comment]
Hi,

I see that you have no change in the `index.html` file (you are supposed to have the same change as in `src/janin.currency.js`, look at https://github.com/MichaelMure/WalletGenerator.net/wiki/How-to-add-a-new-currency#step-five-assemble-the-pieces).

Did you try to generate a wallet and import it in a regular software wallet ?

**Comment by testzcrypto** [comment]
I update index.html manually. Yes, I make all tests, generates wallet and import it in regular software wallet.

**Comment by MichaelMure** [comment]
It's now online ! Thank you :-)

**Comment by testzcrypto** [comment]
Thank you! :-)

**Pull request merged**
