### PR TITLE
Add support for MintCoin

### PR DESCRIPTION
**Pull request by Fuzzbawls**
For Reference:
  Network Version    =    0x33
  Private Key Prefix =    0xb3
  Classic Prefix     =    [67]
  Compressed Prefix  =    T
  Donation Address   =    MdT7t7MhbgQLSdMhHJCyoGHUuniqZDrj4h

More information about MintCoin can be found at www.mintcoinofficial.com
or https://github.com/MintcoinCommunity/Mintcoin-Desktop-Wallet
@MintcoinCommunity

### CODE REVIEW

**Comment by Fuzzbawls** [comment]
@MichaelMure hope this can be pulled in quickly. Did some reading back and saw that you've been rather busy but hope all is well :)

**Comment by MichaelMure** [comment]
Hey, it's now merged and live on https://walletgenerator.net/ !

Sorry for the very long delay.

**Comment by Fuzzbawls** [comment]
@MichaelMure Thanks and hope your're having a good start to 2017! :)

**Comment by MichaelMure** [comment]
I'd say that traveling the world is a pretty good start ;)

**Pull request merged**
