### PR TITLE
Adding support for Vcash

### PR DESCRIPTION
**Pull request by tloriato**
Just added support for this awesome coin.

This was my first time using Git, let me know if I did something wrong, please.

Best Regards,
Tiago

### CODE REVIEW

**Comment by MichaelMure** [comment]
It looks good, it will be in the next release. Thanks !

**Comment by tloriato** [comment]
Any news?

**Comment by MichaelMure** [comment]
Life is very busy at the moment, sorry !

**Comment by MichaelMure** [comment]
Manually merged after fixing the logo size

**Comment by MichaelMure** [comment]
Hey, it's now merged and live on https://walletgenerator.net/ !

Sorry for the very long delay.

**Pull request closed without merging**
