### PR TITLE
Sambacoin e Cryptoescudo support

### PR DESCRIPTION
**Pull request by Marcdnd**
Please add support to Sambacoin and Cryptoescudo

Best regards,

Marcdnd

### CODE REVIEW

**Comment by MichaelMure** [comment]
HI,

Sorry for the long delay, I'll get to it eventually.

Thanks for your contribution !

**Comment by Marcdnd** [comment]
Thanks!

**Comment by MichaelMure** [comment]
Merged, thanks !

**Comment by MichaelMure** [comment]
It's live on https://walletgenerator.net/ :)

**Pull request closed without merging**
