### PR TITLE
Add Cryptonite coin

### PR DESCRIPTION
**Pull request by tnotm**
Hi, I would like to add Cryptonite coin to WalletGenerator.net.

More info on Cryptonite coin can be found at http://cryptonite.info/ and https://bitcointalk.org/index.php?topic=1801595.

Thanks,
John

### CODE REVIEW

**Comment by MichaelMure** [comment]
Sorry to bother you again, could you replicate your change in `src/janin.currency.js` ? Otherwise it will be overwritten the next time the src/ folder is packaged in `index.html`.

**Comment by tnotm** [comment]
Just realized this.... Working on it now.

**Comment by tnotm** [comment]
Done ;)

**Comment by tnotm** [comment]
I don't mind the bother and appreciate your time very much.  Your response and help with allowing me to make this pull request has been wonderful.
Mind if I ask when you think the next release will be?

**Comment by MichaelMure** [comment]
Well, I'm working on a huge project (https://github.com/MichaelMure/TotallyNotArbore) currently, so, huuu, someday ?

**Comment by tnotm** [comment]
Nice! Built on IPFS?  That is really cool.  I approve!  Not much of a dev otherwise I would help :)  Will add it to my Github watch list, and track your progress.

**Comment by MichaelMure** [comment]
Actually there is a lot of non-dev things that you could help with. You have no idea how much that would help ^^

If you are interested, drop by https://gitter.im/TotallyNotArbore/Lobby

**Comment by MichaelMure** [comment]
It's online, sorry for the delay ! :-)

**Pull request merged**
