### PR TITLE
Rubycoin added

### PR DESCRIPTION
**Pull request by Stoner19**

### CODE REVIEW

**Comment by MichaelMure** [comment]
Hi,

You somehow managed to change a lot of files in the repo. Could you provide a pull request with only the change related to adding support for Rubycoin ?

**Comment by Stoner19** [comment]
Hi.  Sorry about that. I'm not overly experienced with git but I'll get it fixed with a new fork and just make ruby coin changes. 

On Oct 17, 2015, at 6:53 AM, Michael Muré notifications@github.com wrote:

Hi,

You somehow managed to change a lot of files in the repo. Could you provide a pull request with only the change related to adding support for Rubycoin ?

**Comment by Stoner19** [comment]
Actually, go ahead and reject, or deny this pull request and I'll fix it properly with a new fork.

**Comment by MichaelMure** [comment]
Let's do that

**Pull request closed without merging**
