### PR TITLE
Updated Emercoin to official lowercase spelling of coin. Also added SpreadCoin & BitcoinDark

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MichaelMure** [comment]
Hi,

Could you also select a wallet background that goes well with the logos ?

**Comment by ghost** [comment]
Thanks for noticing the missing backgrounds. Have I done that correctly? Still learning github :)

**Comment by MichaelMure** [comment]
:+1:

**Comment by MichaelMure** [comment]
Hey, it's live.

**Comment by ghost** [comment]
Great work! Walletgenerator is extremely valuable to many coin communities, thanks for all your efforts!

**Pull request merged**
