### PR TITLE
Add support for Bitcore, CopperCoin, Ember, KittehCoin, NYC, Peercoin, PiggyCoin

### PR DESCRIPTION
**Pull request by jdspringer**
I have added:
Bitcoin Gold, Bitcore, Coppercoin, Ember, Kittehcoin, NYC coin & Piggy coin.

There also was a syntax error in janin.currency.js & index,html from current release that was fixed.

### CODE REVIEW

**Comment by MichaelMure** [comment]
Haha, that was fast. I saw the syntax error when merging the fluxcoin PR but forgot to commit and push before sleeping ...

I see you changed the bitcoin cash logo. Is it really the official one ? I had the impression it is this one: 

Also, you have the name of the currency on the background. There is a discussion about that here: https://github.com/MichaelMure/WalletGenerator.net/issues/97. I would prefer to have a unified solution for all currencies. Or at least a font that match the PUBLIC / PRIVATE text.

Otherwise it's fine, thank you !

**Comment by jdspringer** [comment]
Yes that is the logo on their website. Most of the exchanges show just the round coin. The key thing is the left slanting B! 
I put the name and ticker on the fronts for easy identification. I can remove the names or change the public/private font as well though the original psd/layered file would help if you have it.

**Comment by MichaelMure** [comment]
Yes, please remove the names for now. Also I merged a previous pull-request that add Bitcoin Gold support.

**Comment by jdspringer** [comment]
I removed the names from bitcore,kittehcoin,nyc,ember,piggy,coppercoin 7 updated bitcoin gold images for logo & wallet.

**Comment by jdspringer** [comment]
Think I have it all fixed now, proper bitcoin gold image and wallets updated with no names.

**Comment by MichaelMure** [comment]
Merged manually after some cleaning

**Comment by MichaelMure** [comment]
Hey it's online. Thank you !

**Pull request merged**
