### PR TITLE
Add Russian

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by MichaelMure** [comment]
<3

I'll get to it soon, thanks !

**Comment by MichaelMure** [comment]
Serious thanks for that ! How much time did it took you ?

**Comment by MichaelMure** [comment]
It's live on https://walletgenerator.net/ ! :)

**Comment by UdjinM6** [comment]
> Serious thanks for that ! How much time did it took you ?

Few hours :)

> It's live on https://walletgenerator.net/ ! :)

Cool, thanks! :+1:

**Pull request merged**
