### PR TITLE
Fixed Gridcoin

### PR DESCRIPTION
**Pull request by esspam**
Just noticed, that the Generator wasn't working for Gridcoin, so I fixed it.

### CODE REVIEW

**Comment by MichaelMure** [comment]
What tell you that the generator is not working for gridcoin ? How did you find these new constants ? We added gridcoin ourself so I'm pretty sure it's correct.

**Comment by esspam** [comment]
Hi, sorry for not explaining these things in the first place.
First of all the public addresses seemed wrong to me, as they start with an F or G whereas those in the client start with an R or S.
Nevertheless I tried to import several private keys from the generator into my wallet but it didn't work - "Invalid private key (code -5)"
I found the new constants by following your tutorial on adding new coins (https://github.com/MichaelMure/WalletGenerator.net/wiki/How-to-add-a-new-currency - thanks for that).
Trying out the locally changed version it worked with at least ten different private keys, i.e. they could be imported and the public addresses in the wallet matched those from the generator.
In October last year a new client was released (Gridcoin Research) and the old one is discontinued. Maybe you added the Coin prior to the new client?
Best Regards

**Comment by MichaelMure** [comment]
So that mean that it's a completely different blockchain ?

**Comment by esspam** [comment]
Yes it is. Old coins could be exchanged (via proof-of-burn) into new coins. (see http://wiki.gridcoin.us/Gridcoin-Classic#Gridcoin-Classic_to_Gridcoin-Research_Conversion)

**Comment by MichaelMure** [comment]
Ok, so in that case, could you rename the currency to "GridcoinResearch" ? That way, we actually drop support for the old one.

**Pull request merged**
