### PR TITLE
Added Bitcoin (Segwit), Neo and Bitconnect.

### PR DESCRIPTION
**Pull request by Extamov**

### CODE REVIEW

**Comment by MichaelMure** [comment]
Bitcoin segwit ? I thought it didn't happen. Did I miss something ?

**Comment by MichaelMure** [comment]
On a side note, if you can do separated pull-request next time, it would be easier for me. Thanks :)

**Comment by Extamov** [comment]
@MichaelMure It happened months ago
Bitcoin Segwit needs to replace the normal one
Segwit increases the block size to 2MB
Go to a block explorer you will see that the blocks are a little over 1MB because of Segwit
When Segwit will be implemented to all wallets blocks will be 2MB
It is good for reducing the 20 dollar fees
So yeah.

**Comment by Extamov** [comment]
@MichaelMure What do you mean seperated pull request?
Do you mean by creating 3 pulls, one for each currency.

I will have to fork 3 times for that.

**Comment by MichaelMure** [comment]
You would need 3 branches instead of 3 forks.

**Comment by Extamov** [comment]
@MichaelMure Not sure why you need the coins seperatly.
Should I close this pull request and open 3 requests(recreating fork and branches and also adding seperatly)?
Or leave this one open and you will merge?
BTW the 2 oldest ooen pulls are here from november if not a couple years back please close them

**Comment by MichaelMure** [comment]
It's just that it would be easier for me because I can merge what is ok separately but it's fine, I can deal with it.

Can you give me an official url about bitcoin segwit ? I'm a bit confused by all these forks.

As for the other pull-request, these are not ready to be merged, either because they are incomplete or not at the quality or security level required by a project like this, so someone has to do the work needed. Will you ? Just so you know, I'm running this project alone, for free. I'm not a company, I don't have any employee nor any obligation to work on it. To be completly transparent, I just came back from a year-long travel and I'm unenployed, so free time is not something I have much on my hands.

**Comment by Extamov** [comment]
@MichaelMure

https://bitcoinmagazine.com/articles/segregated-witness-activates-bitcoin-what-expect/
It got activated months ago, we should implement that ASAP.

 "As for the other pull-request, these are not ready to be merged, either because they are incomplete or not at the quality or security level required by a project like this,"
Do you mean that this pull request is not good and not ready to be merged?

"Just so you know, I'm running this project alone, for free. I'm not a company, I don't have any employee nor any obligation to work on it. To be completly transparent, I just came back from a year-long travel and I'm unenployed, so free time is not something I have much on my hands"
Did you tried to find a place to work(That should ease on your life)?

I want this paper wallet to have all the currencies and function better so yeah I will contribute to extend the project.

**Comment by MichaelMure** [comment]
Damn, it's like you try your best to not understand ...

The article you mention is dated from august. [This one](https://news.bitcoin.com/breaking-news-segwit2x-fork-cancelled/) from november say it has been canceled. Am I missing something ? Where can you download a client for this fork ?

**Comment by Extamov** [comment]
@MichaelMure Segwit and Segwit2X are not the same.
Segwit2X is a hard fork while Segwit is a soft fork

Segwit does not equals Segwit2X.

https://bitcoincore.org/en/segwit_adoption/
There are a couple of wallets there that have segwit.

Bitcoin Core have it opt in(Need to use command line)

**Comment by Extamov** [comment]
@MichaelMure Are you even checking the pull request?

Its 2 days and still not merged

**Comment by aawee** [comment]
Hi,
I would love to have a Segwit paper wallet generated by this project. Is there an estimated time for when will be done?
Thank you.

**Comment by Extamov** [comment]
@aawee Yo are not the only one who wants to know

**Comment by aawee** [comment]
Segwit addresses for Bitcoin starts with 3..... not 1.... and fees for sending funds between segwit addresses are cheaper, like 30-40%.
https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki

No need to add new logo or paper design, I think that changing the way that are generated addresses / priv keys are the best way to add segwit for this project.

**Comment by Extamov** [comment]
@aawee The fees are still very high

**Comment by MichaelMure** [comment]
Ha, you just answered the question I was about to ask. It's still for the bitcoin core network but it make sense to have it available for a paper wallet because of the reduced fee.
@ExtendLord did you try to make a transaction to and from a segwit address generated with your changes ? I'm a bit afraid that they changed more than simply the prefix and that the fund would be stuck there.

**Comment by Extamov** [comment]
@MichaelMure I can't even transfer my bitcoins because of the fees.
Oh and if they would change more than thos prefixed it would cause a hard fork since there would not be a backward compatible

**Comment by Extamov** [comment]
@MichaelMure I also checked the private key in a different website that supports segwit and it works

**Comment by aawee** [comment]
Transactions between legacy addresses and segwit addresses are compatible. Vice versa works too.

Please look at this.: https://github.com/coinables/segwitaddress

And I hope you to have some free time to implement segwit to your project.

**Comment by MichaelMure** [comment]
@aawee Thank you

Honestly, I'm not willing to merge the sewgit one without at least one test to and from a generated address. That would be using the visitor as guinea pig without even knowing it.

**Comment by ExtendLord** [comment]
@MichaelMure I'm importing an address to Bitcoin QT now, I will send you an image after I will finish.
You will see that it works.

**Comment by ExtendLord** [comment]
@MichaelMure I have generated a couple of segwit addresses from different places and the private keys of all segwit addresses have both a segwit address and a legacy address.

**Comment by MichaelMure** [comment]
@ExtendLord: why ?

I can't reopen this pull-request and not even pull manually because you deleted the repository ...

**Comment by Extamov** [comment]
@MichaelMure segwit and neo were wrongly coded and are not supported sorry.
The addresses were wrong
The bitconnect was correct so Ive created a new request and closed this one.

**Comment by MichaelMure** [comment]
Ha, i see. Thanks for the effort.

**Pull request closed without merging**
