### PR TITLE
added zcash support

### PR DESCRIPTION
**Pull request by terryxsq**
details https://github.com/MichaelMure/WalletGenerator.net/issues/57#issuecomment-349482198

### CODE REVIEW

**Comment by MichaelMure** [comment]
Thank you for this. I'll need more time to go trough your changes in the address generation part.

In the mean time, could you not have any space changes ? I'd like to keep the maximum of code strictly similar to bitadress.org. And also give a donation address ;)

**Comment by MichaelMure** [comment]
Merged manually, good job :)

**Comment by MichaelMure** [comment]
I also updated the wiki guide to be able to support this kind of currencies: https://github.com/MichaelMure/WalletGenerator.net/wiki/How-to-add-a-new-currency

**Comment by MichaelMure** [comment]
Hey it's online. Thank you !

**Comment by terryxsq** [comment]
Thanks.

**Pull request closed without merging**
