### PR TITLE
Add support for EmerCoin

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MichaelMure** [comment]
Thanks, it will be in the next release :)

**Comment by MichaelMure** [comment]
Ho, and welcome in the big team of free software developer ;-)

**Comment by ghost** [comment]
Thanks for the good wishes :) Any idea how long the changes would take to appear on walletgenerator.net? Interested in providing direct links to the added currency. Thanks again.

**Comment by MichaelMure** [comment]
It's online: https://walletgenerator.net/?currency=EmerCoin

**Comment by ghost** [comment]
Thank you for letting me know!

**Pull request merged**
